<?php
/**
 * AnnotationSortField
 *
 * PHP version 8.5+
 *
 * @category Class
 * @package  Pbxg33k\KavitaClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kavita
 *
 * Kavita provides a set of APIs authenticated via an Auth Key passed in the `x-api-key` header. Generate an Auth Key under User Settings → Manage Auth Keys, paste it into the Authorize panel, and all Try It requests will include it. Assume all fields of a payload are required unless marked optional. Built against v0.9.0.0
 *
 * OpenAPI spec version: 0.9.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.79
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Pbxg33k\KavitaClient\Model;

/**
 * AnnotationSortField Class Doc Comment
 *
 * @category Class
 * @description Members: - &#x60;1&#x60; — Owner - &#x60;2&#x60; — Created - &#x60;3&#x60; — LastModified - &#x60;4&#x60; — Color
 * @package  Pbxg33k\KavitaClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
enum AnnotationSortField: int
{
    case Owner = 1;
    case Created = 2;
    case LastModified = 3;
    case Color = 4;
}
