<?php
/**
 * AppUserSocialPreferences
 *
 * PHP version 5
 *
 * @category Class
 * @package  Pbxg33k\KavitaClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kavita
 *
 * Kavita provides a set of APIs authenticated via an Auth Key passed in the `x-api-key` header. Generate an Auth Key under User Settings → Manage Auth Keys, paste it into the Authorize panel, and all Try It requests will include it. Assume all fields of a payload are required unless marked optional. Built against v0.9.0.0
 *
 * OpenAPI spec version: 0.9.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.79
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Pbxg33k\KavitaClient\Model;

use \ArrayAccess;
use \Pbxg33k\KavitaClient\ObjectSerializer;

/**
 * AppUserSocialPreferences Class Doc Comment
 *
 * @category Class
 * @package  Pbxg33k\KavitaClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AppUserSocialPreferences implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'AppUserSocialPreferences';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'share_reviews' => 'bool',
        'share_annotations' => 'bool',
        'view_other_annotations' => 'bool',
        'social_libraries' => 'int[]',
        'social_max_age_rating' => '\Pbxg33k\KavitaClient\Model\AgeRating',
        'social_include_unknowns' => 'bool',
        'share_profile' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'share_reviews' => null,
        'share_annotations' => null,
        'view_other_annotations' => null,
        'social_libraries' => 'int32',
        'social_max_age_rating' => null,
        'social_include_unknowns' => null,
        'share_profile' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'share_reviews' => 'shareReviews',
        'share_annotations' => 'shareAnnotations',
        'view_other_annotations' => 'viewOtherAnnotations',
        'social_libraries' => 'socialLibraries',
        'social_max_age_rating' => 'socialMaxAgeRating',
        'social_include_unknowns' => 'socialIncludeUnknowns',
        'share_profile' => 'shareProfile'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'share_reviews' => 'setShareReviews',
        'share_annotations' => 'setShareAnnotations',
        'view_other_annotations' => 'setViewOtherAnnotations',
        'social_libraries' => 'setSocialLibraries',
        'social_max_age_rating' => 'setSocialMaxAgeRating',
        'social_include_unknowns' => 'setSocialIncludeUnknowns',
        'share_profile' => 'setShareProfile'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'share_reviews' => 'getShareReviews',
        'share_annotations' => 'getShareAnnotations',
        'view_other_annotations' => 'getViewOtherAnnotations',
        'social_libraries' => 'getSocialLibraries',
        'social_max_age_rating' => 'getSocialMaxAgeRating',
        'social_include_unknowns' => 'getSocialIncludeUnknowns',
        'share_profile' => 'getShareProfile'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['share_reviews'] = isset($data['share_reviews']) ? $data['share_reviews'] : null;
        $this->container['share_annotations'] = isset($data['share_annotations']) ? $data['share_annotations'] : null;
        $this->container['view_other_annotations'] = isset($data['view_other_annotations']) ? $data['view_other_annotations'] : null;
        $this->container['social_libraries'] = isset($data['social_libraries']) ? $data['social_libraries'] : null;
        $this->container['social_max_age_rating'] = isset($data['social_max_age_rating']) ? $data['social_max_age_rating'] : null;
        $this->container['social_include_unknowns'] = isset($data['social_include_unknowns']) ? $data['social_include_unknowns'] : null;
        $this->container['share_profile'] = isset($data['share_profile']) ? $data['share_profile'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets share_reviews
     *
     * @return bool
     */
    public function getShareReviews()
    {
        return $this->container['share_reviews'];
    }

    /**
     * Sets share_reviews
     *
     * @param bool $share_reviews share_reviews
     *
     * @return $this
     */
    public function setShareReviews($share_reviews)
    {
        $this->container['share_reviews'] = $share_reviews;

        return $this;
    }

    /**
     * Gets share_annotations
     *
     * @return bool
     */
    public function getShareAnnotations()
    {
        return $this->container['share_annotations'];
    }

    /**
     * Sets share_annotations
     *
     * @param bool $share_annotations share_annotations
     *
     * @return $this
     */
    public function setShareAnnotations($share_annotations)
    {
        $this->container['share_annotations'] = $share_annotations;

        return $this;
    }

    /**
     * Gets view_other_annotations
     *
     * @return bool
     */
    public function getViewOtherAnnotations()
    {
        return $this->container['view_other_annotations'];
    }

    /**
     * Sets view_other_annotations
     *
     * @param bool $view_other_annotations view_other_annotations
     *
     * @return $this
     */
    public function setViewOtherAnnotations($view_other_annotations)
    {
        $this->container['view_other_annotations'] = $view_other_annotations;

        return $this;
    }

    /**
     * Gets social_libraries
     *
     * @return int[]
     */
    public function getSocialLibraries()
    {
        return $this->container['social_libraries'];
    }

    /**
     * Sets social_libraries
     *
     * @param int[] $social_libraries social_libraries
     *
     * @return $this
     */
    public function setSocialLibraries($social_libraries)
    {
        $this->container['social_libraries'] = $social_libraries;

        return $this;
    }

    /**
     * Gets social_max_age_rating
     *
     * @return \Pbxg33k\KavitaClient\Model\AgeRating
     */
    public function getSocialMaxAgeRating()
    {
        return $this->container['social_max_age_rating'];
    }

    /**
     * Sets social_max_age_rating
     *
     * @param \Pbxg33k\KavitaClient\Model\AgeRating $social_max_age_rating social_max_age_rating
     *
     * @return $this
     */
    public function setSocialMaxAgeRating($social_max_age_rating)
    {
        $this->container['social_max_age_rating'] = $social_max_age_rating;

        return $this;
    }

    /**
     * Gets social_include_unknowns
     *
     * @return bool
     */
    public function getSocialIncludeUnknowns()
    {
        return $this->container['social_include_unknowns'];
    }

    /**
     * Sets social_include_unknowns
     *
     * @param bool $social_include_unknowns social_include_unknowns
     *
     * @return $this
     */
    public function setSocialIncludeUnknowns($social_include_unknowns)
    {
        $this->container['social_include_unknowns'] = $social_include_unknowns;

        return $this;
    }

    /**
     * Gets share_profile
     *
     * @return bool
     */
    public function getShareProfile()
    {
        return $this->container['share_profile'];
    }

    /**
     * Sets share_profile
     *
     * @param bool $share_profile share_profile
     *
     * @return $this
     */
    public function setShareProfile($share_profile)
    {
        $this->container['share_profile'] = $share_profile;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
