<?php
/**
 * BookmarkDto
 *
 * PHP version 5
 *
 * @category Class
 * @package  Pbxg33k\KavitaClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kavita
 *
 * Kavita provides a set of APIs authenticated via an Auth Key passed in the `x-api-key` header. Generate an Auth Key under User Settings → Manage Auth Keys, paste it into the Authorize panel, and all Try It requests will include it. Assume all fields of a payload are required unless marked optional. Built against v0.9.0.0
 *
 * OpenAPI spec version: 0.9.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.79
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Pbxg33k\KavitaClient\Model;

use \ArrayAccess;
use \Pbxg33k\KavitaClient\ObjectSerializer;

/**
 * BookmarkDto Class Doc Comment
 *
 * @category Class
 * @package  Pbxg33k\KavitaClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BookmarkDto implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'BookmarkDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id' => 'int',
        'page' => 'int',
        'volume_id' => 'int',
        'series_id' => 'int',
        'chapter_id' => 'int',
        'image_offset' => 'int',
        'x_path' => 'string',
        'series' => '\Pbxg33k\KavitaClient\Model\SeriesDto',
        'chapter_title' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'id' => 'int32',
        'page' => 'int32',
        'volume_id' => 'int32',
        'series_id' => 'int32',
        'chapter_id' => 'int32',
        'image_offset' => 'int32',
        'x_path' => null,
        'series' => null,
        'chapter_title' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'page' => 'page',
        'volume_id' => 'volumeId',
        'series_id' => 'seriesId',
        'chapter_id' => 'chapterId',
        'image_offset' => 'imageOffset',
        'x_path' => 'xPath',
        'series' => 'series',
        'chapter_title' => 'chapterTitle'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'page' => 'setPage',
        'volume_id' => 'setVolumeId',
        'series_id' => 'setSeriesId',
        'chapter_id' => 'setChapterId',
        'image_offset' => 'setImageOffset',
        'x_path' => 'setXPath',
        'series' => 'setSeries',
        'chapter_title' => 'setChapterTitle'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'page' => 'getPage',
        'volume_id' => 'getVolumeId',
        'series_id' => 'getSeriesId',
        'chapter_id' => 'getChapterId',
        'image_offset' => 'getImageOffset',
        'x_path' => 'getXPath',
        'series' => 'getSeries',
        'chapter_title' => 'getChapterTitle'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['page'] = isset($data['page']) ? $data['page'] : null;
        $this->container['volume_id'] = isset($data['volume_id']) ? $data['volume_id'] : null;
        $this->container['series_id'] = isset($data['series_id']) ? $data['series_id'] : null;
        $this->container['chapter_id'] = isset($data['chapter_id']) ? $data['chapter_id'] : null;
        $this->container['image_offset'] = isset($data['image_offset']) ? $data['image_offset'] : null;
        $this->container['x_path'] = isset($data['x_path']) ? $data['x_path'] : null;
        $this->container['series'] = isset($data['series']) ? $data['series'] : null;
        $this->container['chapter_title'] = isset($data['chapter_title']) ? $data['chapter_title'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['page'] === null) {
            $invalidProperties[] = "'page' can't be null";
        }
        if ($this->container['volume_id'] === null) {
            $invalidProperties[] = "'volume_id' can't be null";
        }
        if ($this->container['series_id'] === null) {
            $invalidProperties[] = "'series_id' can't be null";
        }
        if ($this->container['chapter_id'] === null) {
            $invalidProperties[] = "'chapter_id' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id id
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets page
     *
     * @return int
     */
    public function getPage()
    {
        return $this->container['page'];
    }

    /**
     * Sets page
     *
     * @param int $page page
     *
     * @return $this
     */
    public function setPage($page)
    {
        $this->container['page'] = $page;

        return $this;
    }

    /**
     * Gets volume_id
     *
     * @return int
     */
    public function getVolumeId()
    {
        return $this->container['volume_id'];
    }

    /**
     * Sets volume_id
     *
     * @param int $volume_id volume_id
     *
     * @return $this
     */
    public function setVolumeId($volume_id)
    {
        $this->container['volume_id'] = $volume_id;

        return $this;
    }

    /**
     * Gets series_id
     *
     * @return int
     */
    public function getSeriesId()
    {
        return $this->container['series_id'];
    }

    /**
     * Sets series_id
     *
     * @param int $series_id series_id
     *
     * @return $this
     */
    public function setSeriesId($series_id)
    {
        $this->container['series_id'] = $series_id;

        return $this;
    }

    /**
     * Gets chapter_id
     *
     * @return int
     */
    public function getChapterId()
    {
        return $this->container['chapter_id'];
    }

    /**
     * Sets chapter_id
     *
     * @param int $chapter_id chapter_id
     *
     * @return $this
     */
    public function setChapterId($chapter_id)
    {
        $this->container['chapter_id'] = $chapter_id;

        return $this;
    }

    /**
     * Gets image_offset
     *
     * @return int
     */
    public function getImageOffset()
    {
        return $this->container['image_offset'];
    }

    /**
     * Sets image_offset
     *
     * @param int $image_offset image_offset
     *
     * @return $this
     */
    public function setImageOffset($image_offset)
    {
        $this->container['image_offset'] = $image_offset;

        return $this;
    }

    /**
     * Gets x_path
     *
     * @return string
     */
    public function getXPath()
    {
        return $this->container['x_path'];
    }

    /**
     * Sets x_path
     *
     * @param string $x_path x_path
     *
     * @return $this
     */
    public function setXPath($x_path)
    {
        $this->container['x_path'] = $x_path;

        return $this;
    }

    /**
     * Gets series
     *
     * @return \Pbxg33k\KavitaClient\Model\SeriesDto
     */
    public function getSeries()
    {
        return $this->container['series'];
    }

    /**
     * Sets series
     *
     * @param \Pbxg33k\KavitaClient\Model\SeriesDto $series series
     *
     * @return $this
     */
    public function setSeries($series)
    {
        $this->container['series'] = $series;

        return $this;
    }

    /**
     * Gets chapter_title
     *
     * @return string
     */
    public function getChapterTitle()
    {
        return $this->container['chapter_title'];
    }

    /**
     * Sets chapter_title
     *
     * @param string $chapter_title chapter_title
     *
     * @return $this
     */
    public function setChapterTitle($chapter_title)
    {
        $this->container['chapter_title'] = $chapter_title;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
