<?php
/**
 * BookInfoDto
 *
 * PHP version 5
 *
 * @category Class
 * @package  Pbxg33k\KavitaClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kavita
 *
 * Kavita provides a set of APIs authenticated via an Auth Key passed in the `x-api-key` header. Generate an Auth Key under User Settings → Manage Auth Keys, paste it into the Authorize panel, and all Try It requests will include it. Assume all fields of a payload are required unless marked optional. Built against v0.9.0.0
 *
 * OpenAPI spec version: 0.9.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.79
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Pbxg33k\KavitaClient\Model;

use \ArrayAccess;
use \Pbxg33k\KavitaClient\ObjectSerializer;

/**
 * BookInfoDto Class Doc Comment
 *
 * @category Class
 * @package  Pbxg33k\KavitaClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BookInfoDto implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'BookInfoDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'book_title' => 'string',
        'series_id' => 'int',
        'volume_id' => 'int',
        'series_format' => '\Pbxg33k\KavitaClient\Model\MangaFormat',
        'series_name' => 'string',
        'chapter_number' => 'string',
        'volume_number' => 'string',
        'library_id' => 'int',
        'pages' => 'int',
        'is_special' => 'bool',
        'chapter_title' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'book_title' => null,
        'series_id' => 'int32',
        'volume_id' => 'int32',
        'series_format' => null,
        'series_name' => null,
        'chapter_number' => null,
        'volume_number' => null,
        'library_id' => 'int32',
        'pages' => 'int32',
        'is_special' => null,
        'chapter_title' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'book_title' => 'bookTitle',
        'series_id' => 'seriesId',
        'volume_id' => 'volumeId',
        'series_format' => 'seriesFormat',
        'series_name' => 'seriesName',
        'chapter_number' => 'chapterNumber',
        'volume_number' => 'volumeNumber',
        'library_id' => 'libraryId',
        'pages' => 'pages',
        'is_special' => 'isSpecial',
        'chapter_title' => 'chapterTitle'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'book_title' => 'setBookTitle',
        'series_id' => 'setSeriesId',
        'volume_id' => 'setVolumeId',
        'series_format' => 'setSeriesFormat',
        'series_name' => 'setSeriesName',
        'chapter_number' => 'setChapterNumber',
        'volume_number' => 'setVolumeNumber',
        'library_id' => 'setLibraryId',
        'pages' => 'setPages',
        'is_special' => 'setIsSpecial',
        'chapter_title' => 'setChapterTitle'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'book_title' => 'getBookTitle',
        'series_id' => 'getSeriesId',
        'volume_id' => 'getVolumeId',
        'series_format' => 'getSeriesFormat',
        'series_name' => 'getSeriesName',
        'chapter_number' => 'getChapterNumber',
        'volume_number' => 'getVolumeNumber',
        'library_id' => 'getLibraryId',
        'pages' => 'getPages',
        'is_special' => 'getIsSpecial',
        'chapter_title' => 'getChapterTitle'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['book_title'] = isset($data['book_title']) ? $data['book_title'] : null;
        $this->container['series_id'] = isset($data['series_id']) ? $data['series_id'] : null;
        $this->container['volume_id'] = isset($data['volume_id']) ? $data['volume_id'] : null;
        $this->container['series_format'] = isset($data['series_format']) ? $data['series_format'] : null;
        $this->container['series_name'] = isset($data['series_name']) ? $data['series_name'] : null;
        $this->container['chapter_number'] = isset($data['chapter_number']) ? $data['chapter_number'] : null;
        $this->container['volume_number'] = isset($data['volume_number']) ? $data['volume_number'] : null;
        $this->container['library_id'] = isset($data['library_id']) ? $data['library_id'] : null;
        $this->container['pages'] = isset($data['pages']) ? $data['pages'] : null;
        $this->container['is_special'] = isset($data['is_special']) ? $data['is_special'] : null;
        $this->container['chapter_title'] = isset($data['chapter_title']) ? $data['chapter_title'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets book_title
     *
     * @return string
     */
    public function getBookTitle()
    {
        return $this->container['book_title'];
    }

    /**
     * Sets book_title
     *
     * @param string $book_title book_title
     *
     * @return $this
     */
    public function setBookTitle($book_title)
    {
        $this->container['book_title'] = $book_title;

        return $this;
    }

    /**
     * Gets series_id
     *
     * @return int
     */
    public function getSeriesId()
    {
        return $this->container['series_id'];
    }

    /**
     * Sets series_id
     *
     * @param int $series_id series_id
     *
     * @return $this
     */
    public function setSeriesId($series_id)
    {
        $this->container['series_id'] = $series_id;

        return $this;
    }

    /**
     * Gets volume_id
     *
     * @return int
     */
    public function getVolumeId()
    {
        return $this->container['volume_id'];
    }

    /**
     * Sets volume_id
     *
     * @param int $volume_id volume_id
     *
     * @return $this
     */
    public function setVolumeId($volume_id)
    {
        $this->container['volume_id'] = $volume_id;

        return $this;
    }

    /**
     * Gets series_format
     *
     * @return \Pbxg33k\KavitaClient\Model\MangaFormat
     */
    public function getSeriesFormat()
    {
        return $this->container['series_format'];
    }

    /**
     * Sets series_format
     *
     * @param \Pbxg33k\KavitaClient\Model\MangaFormat $series_format series_format
     *
     * @return $this
     */
    public function setSeriesFormat($series_format)
    {
        $this->container['series_format'] = $series_format;

        return $this;
    }

    /**
     * Gets series_name
     *
     * @return string
     */
    public function getSeriesName()
    {
        return $this->container['series_name'];
    }

    /**
     * Sets series_name
     *
     * @param string $series_name series_name
     *
     * @return $this
     */
    public function setSeriesName($series_name)
    {
        $this->container['series_name'] = $series_name;

        return $this;
    }

    /**
     * Gets chapter_number
     *
     * @return string
     */
    public function getChapterNumber()
    {
        return $this->container['chapter_number'];
    }

    /**
     * Sets chapter_number
     *
     * @param string $chapter_number chapter_number
     *
     * @return $this
     */
    public function setChapterNumber($chapter_number)
    {
        $this->container['chapter_number'] = $chapter_number;

        return $this;
    }

    /**
     * Gets volume_number
     *
     * @return string
     */
    public function getVolumeNumber()
    {
        return $this->container['volume_number'];
    }

    /**
     * Sets volume_number
     *
     * @param string $volume_number volume_number
     *
     * @return $this
     */
    public function setVolumeNumber($volume_number)
    {
        $this->container['volume_number'] = $volume_number;

        return $this;
    }

    /**
     * Gets library_id
     *
     * @return int
     */
    public function getLibraryId()
    {
        return $this->container['library_id'];
    }

    /**
     * Sets library_id
     *
     * @param int $library_id library_id
     *
     * @return $this
     */
    public function setLibraryId($library_id)
    {
        $this->container['library_id'] = $library_id;

        return $this;
    }

    /**
     * Gets pages
     *
     * @return int
     */
    public function getPages()
    {
        return $this->container['pages'];
    }

    /**
     * Sets pages
     *
     * @param int $pages pages
     *
     * @return $this
     */
    public function setPages($pages)
    {
        $this->container['pages'] = $pages;

        return $this;
    }

    /**
     * Gets is_special
     *
     * @return bool
     */
    public function getIsSpecial()
    {
        return $this->container['is_special'];
    }

    /**
     * Sets is_special
     *
     * @param bool $is_special is_special
     *
     * @return $this
     */
    public function setIsSpecial($is_special)
    {
        $this->container['is_special'] = $is_special;

        return $this;
    }

    /**
     * Gets chapter_title
     *
     * @return string
     */
    public function getChapterTitle()
    {
        return $this->container['chapter_title'];
    }

    /**
     * Sets chapter_title
     *
     * @param string $chapter_title chapter_title
     *
     * @return $this
     */
    public function setChapterTitle($chapter_title)
    {
        $this->container['chapter_title'] = $chapter_title;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
