<?php
/**
 * CblImportReason
 *
 * PHP version 5
 *
 * @category Class
 * @package  Pbxg33k\KavitaClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kavita
 *
 * Kavita provides a set of APIs authenticated via an Auth Key passed in the `x-api-key` header. Generate an Auth Key under User Settings → Manage Auth Keys, paste it into the Authorize panel, and all Try It requests will include it. Assume all fields of a payload are required unless marked optional. Built against v0.9.0.0
 *
 * OpenAPI spec version: 0.9.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.79
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Pbxg33k\KavitaClient\Model;
use \Pbxg33k\KavitaClient\ObjectSerializer;

/**
 * CblImportReason Class Doc Comment
 *
 * @category Class
 * @description Members: - &#x60;0&#x60; — Chapter missing (ChapterMissing) - &#x60;1&#x60; — Volume missing (VolumeMissing) - &#x60;2&#x60; — Series missing (SeriesMissing) - &#x60;3&#x60; — Name Conflict (NameConflict) - &#x60;4&#x60; — All Series Missing (AllSeriesMissing) - &#x60;5&#x60; — Empty File (EmptyFile) - &#x60;6&#x60; — Series Collision (SeriesCollision) - &#x60;7&#x60; — All Chapters Missing (AllChapterMissing) - &#x60;8&#x60; — Success - &#x60;9&#x60; — Invalid File (InvalidFile)
 * @package  Pbxg33k\KavitaClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CblImportReason
{
    /**
     * Possible values of this enum
     */
    const 0 = 0;
    const 1 = 1;
    const 2 = 2;
    const 3 = 3;
    const 4 = 4;
    const 5 = 5;
    const 6 = 6;
    const 7 = 7;
    const 8 = 8;
    const 9 = 9;
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::0
            self::1
            self::2
            self::3
            self::4
            self::5
            self::6
            self::7
            self::8
            self::9
        ];
    }
}
