<?php
/**
 * ClientDeviceDto
 *
 * PHP version 5
 *
 * @category Class
 * @package  Pbxg33k\KavitaClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kavita
 *
 * Kavita provides a set of APIs authenticated via an Auth Key passed in the `x-api-key` header. Generate an Auth Key under User Settings → Manage Auth Keys, paste it into the Authorize panel, and all Try It requests will include it. Assume all fields of a payload are required unless marked optional. Built against v0.9.0.0
 *
 * OpenAPI spec version: 0.9.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.79
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Pbxg33k\KavitaClient\Model;

use \ArrayAccess;
use \Pbxg33k\KavitaClient\ObjectSerializer;

/**
 * ClientDeviceDto Class Doc Comment
 *
 * @category Class
 * @package  Pbxg33k\KavitaClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ClientDeviceDto implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ClientDeviceDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id' => 'int',
        'friendly_name' => 'string',
        'ui_fingerprint' => 'string',
        'current_client_info' => '\Pbxg33k\KavitaClient\Model\ClientInfoDto',
        'first_seen_utc' => '\DateTime',
        'last_seen_utc' => '\DateTime',
        'owner_username' => 'string',
        'owner_user_id' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'id' => 'int32',
        'friendly_name' => null,
        'ui_fingerprint' => null,
        'current_client_info' => null,
        'first_seen_utc' => 'date-time',
        'last_seen_utc' => 'date-time',
        'owner_username' => null,
        'owner_user_id' => 'int32'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'friendly_name' => 'friendlyName',
        'ui_fingerprint' => 'uiFingerprint',
        'current_client_info' => 'currentClientInfo',
        'first_seen_utc' => 'firstSeenUtc',
        'last_seen_utc' => 'lastSeenUtc',
        'owner_username' => 'ownerUsername',
        'owner_user_id' => 'ownerUserId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'friendly_name' => 'setFriendlyName',
        'ui_fingerprint' => 'setUiFingerprint',
        'current_client_info' => 'setCurrentClientInfo',
        'first_seen_utc' => 'setFirstSeenUtc',
        'last_seen_utc' => 'setLastSeenUtc',
        'owner_username' => 'setOwnerUsername',
        'owner_user_id' => 'setOwnerUserId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'friendly_name' => 'getFriendlyName',
        'ui_fingerprint' => 'getUiFingerprint',
        'current_client_info' => 'getCurrentClientInfo',
        'first_seen_utc' => 'getFirstSeenUtc',
        'last_seen_utc' => 'getLastSeenUtc',
        'owner_username' => 'getOwnerUsername',
        'owner_user_id' => 'getOwnerUserId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['friendly_name'] = isset($data['friendly_name']) ? $data['friendly_name'] : null;
        $this->container['ui_fingerprint'] = isset($data['ui_fingerprint']) ? $data['ui_fingerprint'] : null;
        $this->container['current_client_info'] = isset($data['current_client_info']) ? $data['current_client_info'] : null;
        $this->container['first_seen_utc'] = isset($data['first_seen_utc']) ? $data['first_seen_utc'] : null;
        $this->container['last_seen_utc'] = isset($data['last_seen_utc']) ? $data['last_seen_utc'] : null;
        $this->container['owner_username'] = isset($data['owner_username']) ? $data['owner_username'] : null;
        $this->container['owner_user_id'] = isset($data['owner_user_id']) ? $data['owner_user_id'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id id
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets friendly_name
     *
     * @return string
     */
    public function getFriendlyName()
    {
        return $this->container['friendly_name'];
    }

    /**
     * Sets friendly_name
     *
     * @param string $friendly_name friendly_name
     *
     * @return $this
     */
    public function setFriendlyName($friendly_name)
    {
        $this->container['friendly_name'] = $friendly_name;

        return $this;
    }

    /**
     * Gets ui_fingerprint
     *
     * @return string
     */
    public function getUiFingerprint()
    {
        return $this->container['ui_fingerprint'];
    }

    /**
     * Sets ui_fingerprint
     *
     * @param string $ui_fingerprint ui_fingerprint
     *
     * @return $this
     */
    public function setUiFingerprint($ui_fingerprint)
    {
        $this->container['ui_fingerprint'] = $ui_fingerprint;

        return $this;
    }

    /**
     * Gets current_client_info
     *
     * @return \Pbxg33k\KavitaClient\Model\ClientInfoDto
     */
    public function getCurrentClientInfo()
    {
        return $this->container['current_client_info'];
    }

    /**
     * Sets current_client_info
     *
     * @param \Pbxg33k\KavitaClient\Model\ClientInfoDto $current_client_info current_client_info
     *
     * @return $this
     */
    public function setCurrentClientInfo($current_client_info)
    {
        $this->container['current_client_info'] = $current_client_info;

        return $this;
    }

    /**
     * Gets first_seen_utc
     *
     * @return \DateTime
     */
    public function getFirstSeenUtc()
    {
        return $this->container['first_seen_utc'];
    }

    /**
     * Sets first_seen_utc
     *
     * @param \DateTime $first_seen_utc first_seen_utc
     *
     * @return $this
     */
    public function setFirstSeenUtc($first_seen_utc)
    {
        $this->container['first_seen_utc'] = $first_seen_utc;

        return $this;
    }

    /**
     * Gets last_seen_utc
     *
     * @return \DateTime
     */
    public function getLastSeenUtc()
    {
        return $this->container['last_seen_utc'];
    }

    /**
     * Sets last_seen_utc
     *
     * @param \DateTime $last_seen_utc last_seen_utc
     *
     * @return $this
     */
    public function setLastSeenUtc($last_seen_utc)
    {
        $this->container['last_seen_utc'] = $last_seen_utc;

        return $this;
    }

    /**
     * Gets owner_username
     *
     * @return string
     */
    public function getOwnerUsername()
    {
        return $this->container['owner_username'];
    }

    /**
     * Sets owner_username
     *
     * @param string $owner_username owner_username
     *
     * @return $this
     */
    public function setOwnerUsername($owner_username)
    {
        $this->container['owner_username'] = $owner_username;

        return $this;
    }

    /**
     * Gets owner_user_id
     *
     * @return int
     */
    public function getOwnerUserId()
    {
        return $this->container['owner_user_id'];
    }

    /**
     * Sets owner_user_id
     *
     * @param int $owner_user_id owner_user_id
     *
     * @return $this
     */
    public function setOwnerUserId($owner_user_id)
    {
        $this->container['owner_user_id'] = $owner_user_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
