<?php
/**
 * SeriesSortField
 *
 * PHP version 8.5+
 *
 * @category Class
 * @package  Pbxg33k\KavitaClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kavita
 *
 * Kavita provides a set of APIs authenticated via an Auth Key passed in the `x-api-key` header. Generate an Auth Key under User Settings → Manage Auth Keys, paste it into the Authorize panel, and all Try It requests will include it. Assume all fields of a payload are required unless marked optional. Built against v0.9.0.0
 *
 * OpenAPI spec version: 0.9.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.79
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Pbxg33k\KavitaClient\Model;

/**
 * SeriesSortField Class Doc Comment
 *
 * @category Class
 * @description Members: - &#x60;1&#x60; — SortName - &#x60;2&#x60; — CreatedDate - &#x60;3&#x60; — LastModifiedDate - &#x60;4&#x60; — LastChapterAdded - &#x60;5&#x60; — TimeToRead - &#x60;6&#x60; — ReleaseYear - &#x60;7&#x60; — ReadProgress - &#x60;8&#x60; — AverageRating - &#x60;9&#x60; — Random - &#x60;10&#x60; — UserRating - &#x60;11&#x60; — UnreadChapterCount
 * @package  Pbxg33k\KavitaClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
enum SeriesSortField: int
{
    case SortName = 1;
    case CreatedDate = 2;
    case LastModifiedDate = 3;
    case LastChapterAdded = 4;
    case TimeToRead = 5;
    case ReleaseYear = 6;
    case ReadProgress = 7;
    case AverageRating = 8;
    case Random = 9;
    case UserRating = 10;
    case UnreadChapterCount = 11;
}
