<?php
/**
 * UpdateRemapRuleDto
 *
 * PHP version 5
 *
 * @category Class
 * @package  Pbxg33k\KavitaClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kavita
 *
 * Kavita provides a set of APIs authenticated via an Auth Key passed in the `x-api-key` header. Generate an Auth Key under User Settings → Manage Auth Keys, paste it into the Authorize panel, and all Try It requests will include it. Assume all fields of a payload are required unless marked optional. Built against v0.9.0.0
 *
 * OpenAPI spec version: 0.9.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.79
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Pbxg33k\KavitaClient\Model;

use \ArrayAccess;
use \Pbxg33k\KavitaClient\ObjectSerializer;

/**
 * UpdateRemapRuleDto Class Doc Comment
 *
 * @category Class
 * @package  Pbxg33k\KavitaClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UpdateRemapRuleDto implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'UpdateRemapRuleDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'cbl_series_name' => 'string',
        'series_id' => 'int',
        'volume_id' => 'int',
        'chapter_id' => 'int',
        'cbl_volume' => 'string',
        'cbl_number' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'cbl_series_name' => null,
        'series_id' => 'int32',
        'volume_id' => 'int32',
        'chapter_id' => 'int32',
        'cbl_volume' => null,
        'cbl_number' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'cbl_series_name' => 'cblSeriesName',
        'series_id' => 'seriesId',
        'volume_id' => 'volumeId',
        'chapter_id' => 'chapterId',
        'cbl_volume' => 'cblVolume',
        'cbl_number' => 'cblNumber'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'cbl_series_name' => 'setCblSeriesName',
        'series_id' => 'setSeriesId',
        'volume_id' => 'setVolumeId',
        'chapter_id' => 'setChapterId',
        'cbl_volume' => 'setCblVolume',
        'cbl_number' => 'setCblNumber'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'cbl_series_name' => 'getCblSeriesName',
        'series_id' => 'getSeriesId',
        'volume_id' => 'getVolumeId',
        'chapter_id' => 'getChapterId',
        'cbl_volume' => 'getCblVolume',
        'cbl_number' => 'getCblNumber'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['cbl_series_name'] = isset($data['cbl_series_name']) ? $data['cbl_series_name'] : null;
        $this->container['series_id'] = isset($data['series_id']) ? $data['series_id'] : null;
        $this->container['volume_id'] = isset($data['volume_id']) ? $data['volume_id'] : null;
        $this->container['chapter_id'] = isset($data['chapter_id']) ? $data['chapter_id'] : null;
        $this->container['cbl_volume'] = isset($data['cbl_volume']) ? $data['cbl_volume'] : null;
        $this->container['cbl_number'] = isset($data['cbl_number']) ? $data['cbl_number'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets cbl_series_name
     *
     * @return string
     */
    public function getCblSeriesName()
    {
        return $this->container['cbl_series_name'];
    }

    /**
     * Sets cbl_series_name
     *
     * @param string $cbl_series_name cbl_series_name
     *
     * @return $this
     */
    public function setCblSeriesName($cbl_series_name)
    {
        $this->container['cbl_series_name'] = $cbl_series_name;

        return $this;
    }

    /**
     * Gets series_id
     *
     * @return int
     */
    public function getSeriesId()
    {
        return $this->container['series_id'];
    }

    /**
     * Sets series_id
     *
     * @param int $series_id series_id
     *
     * @return $this
     */
    public function setSeriesId($series_id)
    {
        $this->container['series_id'] = $series_id;

        return $this;
    }

    /**
     * Gets volume_id
     *
     * @return int
     */
    public function getVolumeId()
    {
        return $this->container['volume_id'];
    }

    /**
     * Sets volume_id
     *
     * @param int $volume_id volume_id
     *
     * @return $this
     */
    public function setVolumeId($volume_id)
    {
        $this->container['volume_id'] = $volume_id;

        return $this;
    }

    /**
     * Gets chapter_id
     *
     * @return int
     */
    public function getChapterId()
    {
        return $this->container['chapter_id'];
    }

    /**
     * Sets chapter_id
     *
     * @param int $chapter_id chapter_id
     *
     * @return $this
     */
    public function setChapterId($chapter_id)
    {
        $this->container['chapter_id'] = $chapter_id;

        return $this;
    }

    /**
     * Gets cbl_volume
     *
     * @return string
     */
    public function getCblVolume()
    {
        return $this->container['cbl_volume'];
    }

    /**
     * Sets cbl_volume
     *
     * @param string $cbl_volume cbl_volume
     *
     * @return $this
     */
    public function setCblVolume($cbl_volume)
    {
        $this->container['cbl_volume'] = $cbl_volume;

        return $this;
    }

    /**
     * Gets cbl_number
     *
     * @return string
     */
    public function getCblNumber()
    {
        return $this->container['cbl_number'];
    }

    /**
     * Sets cbl_number
     *
     * @param string $cbl_number cbl_number
     *
     * @return $this
     */
    public function setCblNumber($cbl_number)
    {
        $this->container['cbl_number'] = $cbl_number;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
