<?php
/**
 * UserPreferencesDto
 *
 * PHP version 5
 *
 * @category Class
 * @package  Pbxg33k\KavitaClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kavita
 *
 * Kavita provides a set of APIs authenticated via an Auth Key passed in the `x-api-key` header. Generate an Auth Key under User Settings → Manage Auth Keys, paste it into the Authorize panel, and all Try It requests will include it. Assume all fields of a payload are required unless marked optional. Built against v0.9.0.0
 *
 * OpenAPI spec version: 0.9.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.79
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Pbxg33k\KavitaClient\Model;

use \ArrayAccess;
use \Pbxg33k\KavitaClient\ObjectSerializer;

/**
 * UserPreferencesDto Class Doc Comment
 *
 * @category Class
 * @package  Pbxg33k\KavitaClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UserPreferencesDto implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'UserPreferencesDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'theme' => '\Pbxg33k\KavitaClient\Model\SiteThemeDto',
        'global_page_layout_mode' => '\Pbxg33k\KavitaClient\Model\PageLayoutMode',
        'blur_unread_summaries' => 'bool',
        'prompt_for_download_size' => 'bool',
        'no_transitions' => 'bool',
        'collapse_series_relationships' => 'bool',
        'locale' => 'string',
        'color_scape_enabled' => 'bool',
        'data_saver' => 'bool',
        'prompt_for_rereads_after' => 'int',
        'custom_key_binds' => '\Pbxg33k\KavitaClient\Model\UserPreferencesDtoCustomKeyBinds',
        'ani_list_scrobbling_enabled' => 'bool',
        'want_to_read_sync' => 'bool',
        'book_reader_highlight_slots' => '\Pbxg33k\KavitaClient\Model\HighlightSlot[]',
        'social_preferences' => '\Pbxg33k\KavitaClient\Model\AppUserSocialPreferences',
        'opds_preferences' => '\Pbxg33k\KavitaClient\Model\AppUserOpdsPreferences'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'theme' => null,
        'global_page_layout_mode' => null,
        'blur_unread_summaries' => null,
        'prompt_for_download_size' => null,
        'no_transitions' => null,
        'collapse_series_relationships' => null,
        'locale' => null,
        'color_scape_enabled' => null,
        'data_saver' => null,
        'prompt_for_rereads_after' => 'int32',
        'custom_key_binds' => null,
        'ani_list_scrobbling_enabled' => null,
        'want_to_read_sync' => null,
        'book_reader_highlight_slots' => null,
        'social_preferences' => null,
        'opds_preferences' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'theme' => 'theme',
        'global_page_layout_mode' => 'globalPageLayoutMode',
        'blur_unread_summaries' => 'blurUnreadSummaries',
        'prompt_for_download_size' => 'promptForDownloadSize',
        'no_transitions' => 'noTransitions',
        'collapse_series_relationships' => 'collapseSeriesRelationships',
        'locale' => 'locale',
        'color_scape_enabled' => 'colorScapeEnabled',
        'data_saver' => 'dataSaver',
        'prompt_for_rereads_after' => 'promptForRereadsAfter',
        'custom_key_binds' => 'customKeyBinds',
        'ani_list_scrobbling_enabled' => 'aniListScrobblingEnabled',
        'want_to_read_sync' => 'wantToReadSync',
        'book_reader_highlight_slots' => 'bookReaderHighlightSlots',
        'social_preferences' => 'socialPreferences',
        'opds_preferences' => 'opdsPreferences'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'theme' => 'setTheme',
        'global_page_layout_mode' => 'setGlobalPageLayoutMode',
        'blur_unread_summaries' => 'setBlurUnreadSummaries',
        'prompt_for_download_size' => 'setPromptForDownloadSize',
        'no_transitions' => 'setNoTransitions',
        'collapse_series_relationships' => 'setCollapseSeriesRelationships',
        'locale' => 'setLocale',
        'color_scape_enabled' => 'setColorScapeEnabled',
        'data_saver' => 'setDataSaver',
        'prompt_for_rereads_after' => 'setPromptForRereadsAfter',
        'custom_key_binds' => 'setCustomKeyBinds',
        'ani_list_scrobbling_enabled' => 'setAniListScrobblingEnabled',
        'want_to_read_sync' => 'setWantToReadSync',
        'book_reader_highlight_slots' => 'setBookReaderHighlightSlots',
        'social_preferences' => 'setSocialPreferences',
        'opds_preferences' => 'setOpdsPreferences'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'theme' => 'getTheme',
        'global_page_layout_mode' => 'getGlobalPageLayoutMode',
        'blur_unread_summaries' => 'getBlurUnreadSummaries',
        'prompt_for_download_size' => 'getPromptForDownloadSize',
        'no_transitions' => 'getNoTransitions',
        'collapse_series_relationships' => 'getCollapseSeriesRelationships',
        'locale' => 'getLocale',
        'color_scape_enabled' => 'getColorScapeEnabled',
        'data_saver' => 'getDataSaver',
        'prompt_for_rereads_after' => 'getPromptForRereadsAfter',
        'custom_key_binds' => 'getCustomKeyBinds',
        'ani_list_scrobbling_enabled' => 'getAniListScrobblingEnabled',
        'want_to_read_sync' => 'getWantToReadSync',
        'book_reader_highlight_slots' => 'getBookReaderHighlightSlots',
        'social_preferences' => 'getSocialPreferences',
        'opds_preferences' => 'getOpdsPreferences'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['theme'] = isset($data['theme']) ? $data['theme'] : null;
        $this->container['global_page_layout_mode'] = isset($data['global_page_layout_mode']) ? $data['global_page_layout_mode'] : null;
        $this->container['blur_unread_summaries'] = isset($data['blur_unread_summaries']) ? $data['blur_unread_summaries'] : null;
        $this->container['prompt_for_download_size'] = isset($data['prompt_for_download_size']) ? $data['prompt_for_download_size'] : null;
        $this->container['no_transitions'] = isset($data['no_transitions']) ? $data['no_transitions'] : null;
        $this->container['collapse_series_relationships'] = isset($data['collapse_series_relationships']) ? $data['collapse_series_relationships'] : null;
        $this->container['locale'] = isset($data['locale']) ? $data['locale'] : null;
        $this->container['color_scape_enabled'] = isset($data['color_scape_enabled']) ? $data['color_scape_enabled'] : null;
        $this->container['data_saver'] = isset($data['data_saver']) ? $data['data_saver'] : null;
        $this->container['prompt_for_rereads_after'] = isset($data['prompt_for_rereads_after']) ? $data['prompt_for_rereads_after'] : null;
        $this->container['custom_key_binds'] = isset($data['custom_key_binds']) ? $data['custom_key_binds'] : null;
        $this->container['ani_list_scrobbling_enabled'] = isset($data['ani_list_scrobbling_enabled']) ? $data['ani_list_scrobbling_enabled'] : null;
        $this->container['want_to_read_sync'] = isset($data['want_to_read_sync']) ? $data['want_to_read_sync'] : null;
        $this->container['book_reader_highlight_slots'] = isset($data['book_reader_highlight_slots']) ? $data['book_reader_highlight_slots'] : null;
        $this->container['social_preferences'] = isset($data['social_preferences']) ? $data['social_preferences'] : null;
        $this->container['opds_preferences'] = isset($data['opds_preferences']) ? $data['opds_preferences'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['theme'] === null) {
            $invalidProperties[] = "'theme' can't be null";
        }
        if ($this->container['blur_unread_summaries'] === null) {
            $invalidProperties[] = "'blur_unread_summaries' can't be null";
        }
        if ($this->container['prompt_for_download_size'] === null) {
            $invalidProperties[] = "'prompt_for_download_size' can't be null";
        }
        if ($this->container['no_transitions'] === null) {
            $invalidProperties[] = "'no_transitions' can't be null";
        }
        if ($this->container['collapse_series_relationships'] === null) {
            $invalidProperties[] = "'collapse_series_relationships' can't be null";
        }
        if ($this->container['locale'] === null) {
            $invalidProperties[] = "'locale' can't be null";
        }
        if ($this->container['color_scape_enabled'] === null) {
            $invalidProperties[] = "'color_scape_enabled' can't be null";
        }
        if ($this->container['data_saver'] === null) {
            $invalidProperties[] = "'data_saver' can't be null";
        }
        if ($this->container['prompt_for_rereads_after'] === null) {
            $invalidProperties[] = "'prompt_for_rereads_after' can't be null";
        }
        if ($this->container['custom_key_binds'] === null) {
            $invalidProperties[] = "'custom_key_binds' can't be null";
        }
        if ($this->container['book_reader_highlight_slots'] === null) {
            $invalidProperties[] = "'book_reader_highlight_slots' can't be null";
        }
        if ($this->container['social_preferences'] === null) {
            $invalidProperties[] = "'social_preferences' can't be null";
        }
        if ($this->container['opds_preferences'] === null) {
            $invalidProperties[] = "'opds_preferences' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets theme
     *
     * @return \Pbxg33k\KavitaClient\Model\SiteThemeDto
     */
    public function getTheme()
    {
        return $this->container['theme'];
    }

    /**
     * Sets theme
     *
     * @param \Pbxg33k\KavitaClient\Model\SiteThemeDto $theme theme
     *
     * @return $this
     */
    public function setTheme($theme)
    {
        $this->container['theme'] = $theme;

        return $this;
    }

    /**
     * Gets global_page_layout_mode
     *
     * @return \Pbxg33k\KavitaClient\Model\PageLayoutMode
     */
    public function getGlobalPageLayoutMode()
    {
        return $this->container['global_page_layout_mode'];
    }

    /**
     * Sets global_page_layout_mode
     *
     * @param \Pbxg33k\KavitaClient\Model\PageLayoutMode $global_page_layout_mode global_page_layout_mode
     *
     * @return $this
     */
    public function setGlobalPageLayoutMode($global_page_layout_mode)
    {
        $this->container['global_page_layout_mode'] = $global_page_layout_mode;

        return $this;
    }

    /**
     * Gets blur_unread_summaries
     *
     * @return bool
     */
    public function getBlurUnreadSummaries()
    {
        return $this->container['blur_unread_summaries'];
    }

    /**
     * Sets blur_unread_summaries
     *
     * @param bool $blur_unread_summaries blur_unread_summaries
     *
     * @return $this
     */
    public function setBlurUnreadSummaries($blur_unread_summaries)
    {
        $this->container['blur_unread_summaries'] = $blur_unread_summaries;

        return $this;
    }

    /**
     * Gets prompt_for_download_size
     *
     * @return bool
     */
    public function getPromptForDownloadSize()
    {
        return $this->container['prompt_for_download_size'];
    }

    /**
     * Sets prompt_for_download_size
     *
     * @param bool $prompt_for_download_size prompt_for_download_size
     *
     * @return $this
     */
    public function setPromptForDownloadSize($prompt_for_download_size)
    {
        $this->container['prompt_for_download_size'] = $prompt_for_download_size;

        return $this;
    }

    /**
     * Gets no_transitions
     *
     * @return bool
     */
    public function getNoTransitions()
    {
        return $this->container['no_transitions'];
    }

    /**
     * Sets no_transitions
     *
     * @param bool $no_transitions no_transitions
     *
     * @return $this
     */
    public function setNoTransitions($no_transitions)
    {
        $this->container['no_transitions'] = $no_transitions;

        return $this;
    }

    /**
     * Gets collapse_series_relationships
     *
     * @return bool
     */
    public function getCollapseSeriesRelationships()
    {
        return $this->container['collapse_series_relationships'];
    }

    /**
     * Sets collapse_series_relationships
     *
     * @param bool $collapse_series_relationships collapse_series_relationships
     *
     * @return $this
     */
    public function setCollapseSeriesRelationships($collapse_series_relationships)
    {
        $this->container['collapse_series_relationships'] = $collapse_series_relationships;

        return $this;
    }

    /**
     * Gets locale
     *
     * @return string
     */
    public function getLocale()
    {
        return $this->container['locale'];
    }

    /**
     * Sets locale
     *
     * @param string $locale locale
     *
     * @return $this
     */
    public function setLocale($locale)
    {
        $this->container['locale'] = $locale;

        return $this;
    }

    /**
     * Gets color_scape_enabled
     *
     * @return bool
     */
    public function getColorScapeEnabled()
    {
        return $this->container['color_scape_enabled'];
    }

    /**
     * Sets color_scape_enabled
     *
     * @param bool $color_scape_enabled color_scape_enabled
     *
     * @return $this
     */
    public function setColorScapeEnabled($color_scape_enabled)
    {
        $this->container['color_scape_enabled'] = $color_scape_enabled;

        return $this;
    }

    /**
     * Gets data_saver
     *
     * @return bool
     */
    public function getDataSaver()
    {
        return $this->container['data_saver'];
    }

    /**
     * Sets data_saver
     *
     * @param bool $data_saver data_saver
     *
     * @return $this
     */
    public function setDataSaver($data_saver)
    {
        $this->container['data_saver'] = $data_saver;

        return $this;
    }

    /**
     * Gets prompt_for_rereads_after
     *
     * @return int
     */
    public function getPromptForRereadsAfter()
    {
        return $this->container['prompt_for_rereads_after'];
    }

    /**
     * Sets prompt_for_rereads_after
     *
     * @param int $prompt_for_rereads_after prompt_for_rereads_after
     *
     * @return $this
     */
    public function setPromptForRereadsAfter($prompt_for_rereads_after)
    {
        $this->container['prompt_for_rereads_after'] = $prompt_for_rereads_after;

        return $this;
    }

    /**
     * Gets custom_key_binds
     *
     * @return \Pbxg33k\KavitaClient\Model\UserPreferencesDtoCustomKeyBinds
     */
    public function getCustomKeyBinds()
    {
        return $this->container['custom_key_binds'];
    }

    /**
     * Sets custom_key_binds
     *
     * @param \Pbxg33k\KavitaClient\Model\UserPreferencesDtoCustomKeyBinds $custom_key_binds custom_key_binds
     *
     * @return $this
     */
    public function setCustomKeyBinds($custom_key_binds)
    {
        $this->container['custom_key_binds'] = $custom_key_binds;

        return $this;
    }

    /**
     * Gets ani_list_scrobbling_enabled
     *
     * @return bool
     */
    public function getAniListScrobblingEnabled()
    {
        return $this->container['ani_list_scrobbling_enabled'];
    }

    /**
     * Sets ani_list_scrobbling_enabled
     *
     * @param bool $ani_list_scrobbling_enabled ani_list_scrobbling_enabled
     *
     * @return $this
     */
    public function setAniListScrobblingEnabled($ani_list_scrobbling_enabled)
    {
        $this->container['ani_list_scrobbling_enabled'] = $ani_list_scrobbling_enabled;

        return $this;
    }

    /**
     * Gets want_to_read_sync
     *
     * @return bool
     */
    public function getWantToReadSync()
    {
        return $this->container['want_to_read_sync'];
    }

    /**
     * Sets want_to_read_sync
     *
     * @param bool $want_to_read_sync want_to_read_sync
     *
     * @return $this
     */
    public function setWantToReadSync($want_to_read_sync)
    {
        $this->container['want_to_read_sync'] = $want_to_read_sync;

        return $this;
    }

    /**
     * Gets book_reader_highlight_slots
     *
     * @return \Pbxg33k\KavitaClient\Model\HighlightSlot[]
     */
    public function getBookReaderHighlightSlots()
    {
        return $this->container['book_reader_highlight_slots'];
    }

    /**
     * Sets book_reader_highlight_slots
     *
     * @param \Pbxg33k\KavitaClient\Model\HighlightSlot[] $book_reader_highlight_slots book_reader_highlight_slots
     *
     * @return $this
     */
    public function setBookReaderHighlightSlots($book_reader_highlight_slots)
    {
        $this->container['book_reader_highlight_slots'] = $book_reader_highlight_slots;

        return $this;
    }

    /**
     * Gets social_preferences
     *
     * @return \Pbxg33k\KavitaClient\Model\AppUserSocialPreferences
     */
    public function getSocialPreferences()
    {
        return $this->container['social_preferences'];
    }

    /**
     * Sets social_preferences
     *
     * @param \Pbxg33k\KavitaClient\Model\AppUserSocialPreferences $social_preferences social_preferences
     *
     * @return $this
     */
    public function setSocialPreferences($social_preferences)
    {
        $this->container['social_preferences'] = $social_preferences;

        return $this;
    }

    /**
     * Gets opds_preferences
     *
     * @return \Pbxg33k\KavitaClient\Model\AppUserOpdsPreferences
     */
    public function getOpdsPreferences()
    {
        return $this->container['opds_preferences'];
    }

    /**
     * Sets opds_preferences
     *
     * @param \Pbxg33k\KavitaClient\Model\AppUserOpdsPreferences $opds_preferences opds_preferences
     *
     * @return $this
     */
    public function setOpdsPreferences($opds_preferences)
    {
        $this->container['opds_preferences'] = $opds_preferences;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
