<?php
/**
 * VolumeDto
 *
 * PHP version 5
 *
 * @category Class
 * @package  Pbxg33k\KavitaClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kavita
 *
 * Kavita provides a set of APIs authenticated via an Auth Key passed in the `x-api-key` header. Generate an Auth Key under User Settings → Manage Auth Keys, paste it into the Authorize panel, and all Try It requests will include it. Assume all fields of a payload are required unless marked optional. Built against v0.9.0.0
 *
 * OpenAPI spec version: 0.9.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.79
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Pbxg33k\KavitaClient\Model;

use \ArrayAccess;
use \Pbxg33k\KavitaClient\ObjectSerializer;

/**
 * VolumeDto Class Doc Comment
 *
 * @category Class
 * @package  Pbxg33k\KavitaClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class VolumeDto implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'VolumeDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id' => 'int',
        'min_number' => 'float',
        'max_number' => 'float',
        'name' => 'string',
        'number' => 'int',
        'pages' => 'int',
        'pages_read' => 'int',
        'last_modified_utc' => '\DateTime',
        'created_utc' => '\DateTime',
        'created' => '\DateTime',
        'last_modified' => '\DateTime',
        'series_id' => 'int',
        'chapters' => '\Pbxg33k\KavitaClient\Model\ChapterDto[]',
        'min_hours_to_read' => 'int',
        'max_hours_to_read' => 'int',
        'avg_hours_to_read' => 'float',
        'word_count' => 'int',
        'cover_image' => 'string',
        'primary_color' => 'string',
        'secondary_color' => 'string',
        'ani_list_id' => 'int',
        'mal_id' => 'int',
        'hardcover_id' => 'int',
        'metron_id' => 'int',
        'comic_vine_id' => 'string',
        'manga_baka_id' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'id' => 'int32',
        'min_number' => 'float',
        'max_number' => 'float',
        'name' => null,
        'number' => 'int32',
        'pages' => 'int32',
        'pages_read' => 'int32',
        'last_modified_utc' => 'date-time',
        'created_utc' => 'date-time',
        'created' => 'date-time',
        'last_modified' => 'date-time',
        'series_id' => 'int32',
        'chapters' => null,
        'min_hours_to_read' => 'int32',
        'max_hours_to_read' => 'int32',
        'avg_hours_to_read' => 'float',
        'word_count' => 'int64',
        'cover_image' => null,
        'primary_color' => null,
        'secondary_color' => null,
        'ani_list_id' => 'int32',
        'mal_id' => 'int64',
        'hardcover_id' => 'int32',
        'metron_id' => 'int64',
        'comic_vine_id' => null,
        'manga_baka_id' => 'int64'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'min_number' => 'minNumber',
        'max_number' => 'maxNumber',
        'name' => 'name',
        'number' => 'number',
        'pages' => 'pages',
        'pages_read' => 'pagesRead',
        'last_modified_utc' => 'lastModifiedUtc',
        'created_utc' => 'createdUtc',
        'created' => 'created',
        'last_modified' => 'lastModified',
        'series_id' => 'seriesId',
        'chapters' => 'chapters',
        'min_hours_to_read' => 'minHoursToRead',
        'max_hours_to_read' => 'maxHoursToRead',
        'avg_hours_to_read' => 'avgHoursToRead',
        'word_count' => 'wordCount',
        'cover_image' => 'coverImage',
        'primary_color' => 'primaryColor',
        'secondary_color' => 'secondaryColor',
        'ani_list_id' => 'aniListId',
        'mal_id' => 'malId',
        'hardcover_id' => 'hardcoverId',
        'metron_id' => 'metronId',
        'comic_vine_id' => 'comicVineId',
        'manga_baka_id' => 'mangaBakaId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'min_number' => 'setMinNumber',
        'max_number' => 'setMaxNumber',
        'name' => 'setName',
        'number' => 'setNumber',
        'pages' => 'setPages',
        'pages_read' => 'setPagesRead',
        'last_modified_utc' => 'setLastModifiedUtc',
        'created_utc' => 'setCreatedUtc',
        'created' => 'setCreated',
        'last_modified' => 'setLastModified',
        'series_id' => 'setSeriesId',
        'chapters' => 'setChapters',
        'min_hours_to_read' => 'setMinHoursToRead',
        'max_hours_to_read' => 'setMaxHoursToRead',
        'avg_hours_to_read' => 'setAvgHoursToRead',
        'word_count' => 'setWordCount',
        'cover_image' => 'setCoverImage',
        'primary_color' => 'setPrimaryColor',
        'secondary_color' => 'setSecondaryColor',
        'ani_list_id' => 'setAniListId',
        'mal_id' => 'setMalId',
        'hardcover_id' => 'setHardcoverId',
        'metron_id' => 'setMetronId',
        'comic_vine_id' => 'setComicVineId',
        'manga_baka_id' => 'setMangaBakaId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'min_number' => 'getMinNumber',
        'max_number' => 'getMaxNumber',
        'name' => 'getName',
        'number' => 'getNumber',
        'pages' => 'getPages',
        'pages_read' => 'getPagesRead',
        'last_modified_utc' => 'getLastModifiedUtc',
        'created_utc' => 'getCreatedUtc',
        'created' => 'getCreated',
        'last_modified' => 'getLastModified',
        'series_id' => 'getSeriesId',
        'chapters' => 'getChapters',
        'min_hours_to_read' => 'getMinHoursToRead',
        'max_hours_to_read' => 'getMaxHoursToRead',
        'avg_hours_to_read' => 'getAvgHoursToRead',
        'word_count' => 'getWordCount',
        'cover_image' => 'getCoverImage',
        'primary_color' => 'getPrimaryColor',
        'secondary_color' => 'getSecondaryColor',
        'ani_list_id' => 'getAniListId',
        'mal_id' => 'getMalId',
        'hardcover_id' => 'getHardcoverId',
        'metron_id' => 'getMetronId',
        'comic_vine_id' => 'getComicVineId',
        'manga_baka_id' => 'getMangaBakaId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['min_number'] = isset($data['min_number']) ? $data['min_number'] : null;
        $this->container['max_number'] = isset($data['max_number']) ? $data['max_number'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['number'] = isset($data['number']) ? $data['number'] : null;
        $this->container['pages'] = isset($data['pages']) ? $data['pages'] : null;
        $this->container['pages_read'] = isset($data['pages_read']) ? $data['pages_read'] : null;
        $this->container['last_modified_utc'] = isset($data['last_modified_utc']) ? $data['last_modified_utc'] : null;
        $this->container['created_utc'] = isset($data['created_utc']) ? $data['created_utc'] : null;
        $this->container['created'] = isset($data['created']) ? $data['created'] : null;
        $this->container['last_modified'] = isset($data['last_modified']) ? $data['last_modified'] : null;
        $this->container['series_id'] = isset($data['series_id']) ? $data['series_id'] : null;
        $this->container['chapters'] = isset($data['chapters']) ? $data['chapters'] : null;
        $this->container['min_hours_to_read'] = isset($data['min_hours_to_read']) ? $data['min_hours_to_read'] : null;
        $this->container['max_hours_to_read'] = isset($data['max_hours_to_read']) ? $data['max_hours_to_read'] : null;
        $this->container['avg_hours_to_read'] = isset($data['avg_hours_to_read']) ? $data['avg_hours_to_read'] : null;
        $this->container['word_count'] = isset($data['word_count']) ? $data['word_count'] : null;
        $this->container['cover_image'] = isset($data['cover_image']) ? $data['cover_image'] : null;
        $this->container['primary_color'] = isset($data['primary_color']) ? $data['primary_color'] : null;
        $this->container['secondary_color'] = isset($data['secondary_color']) ? $data['secondary_color'] : null;
        $this->container['ani_list_id'] = isset($data['ani_list_id']) ? $data['ani_list_id'] : null;
        $this->container['mal_id'] = isset($data['mal_id']) ? $data['mal_id'] : null;
        $this->container['hardcover_id'] = isset($data['hardcover_id']) ? $data['hardcover_id'] : null;
        $this->container['metron_id'] = isset($data['metron_id']) ? $data['metron_id'] : null;
        $this->container['comic_vine_id'] = isset($data['comic_vine_id']) ? $data['comic_vine_id'] : null;
        $this->container['manga_baka_id'] = isset($data['manga_baka_id']) ? $data['manga_baka_id'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id id
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets min_number
     *
     * @return float
     */
    public function getMinNumber()
    {
        return $this->container['min_number'];
    }

    /**
     * Sets min_number
     *
     * @param float $min_number min_number
     *
     * @return $this
     */
    public function setMinNumber($min_number)
    {
        $this->container['min_number'] = $min_number;

        return $this;
    }

    /**
     * Gets max_number
     *
     * @return float
     */
    public function getMaxNumber()
    {
        return $this->container['max_number'];
    }

    /**
     * Sets max_number
     *
     * @param float $max_number max_number
     *
     * @return $this
     */
    public function setMaxNumber($max_number)
    {
        $this->container['max_number'] = $max_number;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets number
     *
     * @return int
     */
    public function getNumber()
    {
        return $this->container['number'];
    }

    /**
     * Sets number
     *
     * @param int $number number
     *
     * @return $this
     */
    public function setNumber($number)
    {
        $this->container['number'] = $number;

        return $this;
    }

    /**
     * Gets pages
     *
     * @return int
     */
    public function getPages()
    {
        return $this->container['pages'];
    }

    /**
     * Sets pages
     *
     * @param int $pages pages
     *
     * @return $this
     */
    public function setPages($pages)
    {
        $this->container['pages'] = $pages;

        return $this;
    }

    /**
     * Gets pages_read
     *
     * @return int
     */
    public function getPagesRead()
    {
        return $this->container['pages_read'];
    }

    /**
     * Sets pages_read
     *
     * @param int $pages_read pages_read
     *
     * @return $this
     */
    public function setPagesRead($pages_read)
    {
        $this->container['pages_read'] = $pages_read;

        return $this;
    }

    /**
     * Gets last_modified_utc
     *
     * @return \DateTime
     */
    public function getLastModifiedUtc()
    {
        return $this->container['last_modified_utc'];
    }

    /**
     * Sets last_modified_utc
     *
     * @param \DateTime $last_modified_utc last_modified_utc
     *
     * @return $this
     */
    public function setLastModifiedUtc($last_modified_utc)
    {
        $this->container['last_modified_utc'] = $last_modified_utc;

        return $this;
    }

    /**
     * Gets created_utc
     *
     * @return \DateTime
     */
    public function getCreatedUtc()
    {
        return $this->container['created_utc'];
    }

    /**
     * Sets created_utc
     *
     * @param \DateTime $created_utc created_utc
     *
     * @return $this
     */
    public function setCreatedUtc($created_utc)
    {
        $this->container['created_utc'] = $created_utc;

        return $this;
    }

    /**
     * Gets created
     *
     * @return \DateTime
     */
    public function getCreated()
    {
        return $this->container['created'];
    }

    /**
     * Sets created
     *
     * @param \DateTime $created created
     *
     * @return $this
     */
    public function setCreated($created)
    {
        $this->container['created'] = $created;

        return $this;
    }

    /**
     * Gets last_modified
     *
     * @return \DateTime
     */
    public function getLastModified()
    {
        return $this->container['last_modified'];
    }

    /**
     * Sets last_modified
     *
     * @param \DateTime $last_modified last_modified
     *
     * @return $this
     */
    public function setLastModified($last_modified)
    {
        $this->container['last_modified'] = $last_modified;

        return $this;
    }

    /**
     * Gets series_id
     *
     * @return int
     */
    public function getSeriesId()
    {
        return $this->container['series_id'];
    }

    /**
     * Sets series_id
     *
     * @param int $series_id series_id
     *
     * @return $this
     */
    public function setSeriesId($series_id)
    {
        $this->container['series_id'] = $series_id;

        return $this;
    }

    /**
     * Gets chapters
     *
     * @return \Pbxg33k\KavitaClient\Model\ChapterDto[]
     */
    public function getChapters()
    {
        return $this->container['chapters'];
    }

    /**
     * Sets chapters
     *
     * @param \Pbxg33k\KavitaClient\Model\ChapterDto[] $chapters chapters
     *
     * @return $this
     */
    public function setChapters($chapters)
    {
        $this->container['chapters'] = $chapters;

        return $this;
    }

    /**
     * Gets min_hours_to_read
     *
     * @return int
     */
    public function getMinHoursToRead()
    {
        return $this->container['min_hours_to_read'];
    }

    /**
     * Sets min_hours_to_read
     *
     * @param int $min_hours_to_read min_hours_to_read
     *
     * @return $this
     */
    public function setMinHoursToRead($min_hours_to_read)
    {
        $this->container['min_hours_to_read'] = $min_hours_to_read;

        return $this;
    }

    /**
     * Gets max_hours_to_read
     *
     * @return int
     */
    public function getMaxHoursToRead()
    {
        return $this->container['max_hours_to_read'];
    }

    /**
     * Sets max_hours_to_read
     *
     * @param int $max_hours_to_read max_hours_to_read
     *
     * @return $this
     */
    public function setMaxHoursToRead($max_hours_to_read)
    {
        $this->container['max_hours_to_read'] = $max_hours_to_read;

        return $this;
    }

    /**
     * Gets avg_hours_to_read
     *
     * @return float
     */
    public function getAvgHoursToRead()
    {
        return $this->container['avg_hours_to_read'];
    }

    /**
     * Sets avg_hours_to_read
     *
     * @param float $avg_hours_to_read avg_hours_to_read
     *
     * @return $this
     */
    public function setAvgHoursToRead($avg_hours_to_read)
    {
        $this->container['avg_hours_to_read'] = $avg_hours_to_read;

        return $this;
    }

    /**
     * Gets word_count
     *
     * @return int
     */
    public function getWordCount()
    {
        return $this->container['word_count'];
    }

    /**
     * Sets word_count
     *
     * @param int $word_count word_count
     *
     * @return $this
     */
    public function setWordCount($word_count)
    {
        $this->container['word_count'] = $word_count;

        return $this;
    }

    /**
     * Gets cover_image
     *
     * @return string
     */
    public function getCoverImage()
    {
        return $this->container['cover_image'];
    }

    /**
     * Sets cover_image
     *
     * @param string $cover_image cover_image
     *
     * @return $this
     */
    public function setCoverImage($cover_image)
    {
        $this->container['cover_image'] = $cover_image;

        return $this;
    }

    /**
     * Gets primary_color
     *
     * @return string
     */
    public function getPrimaryColor()
    {
        return $this->container['primary_color'];
    }

    /**
     * Sets primary_color
     *
     * @param string $primary_color primary_color
     *
     * @return $this
     */
    public function setPrimaryColor($primary_color)
    {
        $this->container['primary_color'] = $primary_color;

        return $this;
    }

    /**
     * Gets secondary_color
     *
     * @return string
     */
    public function getSecondaryColor()
    {
        return $this->container['secondary_color'];
    }

    /**
     * Sets secondary_color
     *
     * @param string $secondary_color secondary_color
     *
     * @return $this
     */
    public function setSecondaryColor($secondary_color)
    {
        $this->container['secondary_color'] = $secondary_color;

        return $this;
    }

    /**
     * Gets ani_list_id
     *
     * @return int
     */
    public function getAniListId()
    {
        return $this->container['ani_list_id'];
    }

    /**
     * Sets ani_list_id
     *
     * @param int $ani_list_id ani_list_id
     *
     * @return $this
     */
    public function setAniListId($ani_list_id)
    {
        $this->container['ani_list_id'] = $ani_list_id;

        return $this;
    }

    /**
     * Gets mal_id
     *
     * @return int
     */
    public function getMalId()
    {
        return $this->container['mal_id'];
    }

    /**
     * Sets mal_id
     *
     * @param int $mal_id mal_id
     *
     * @return $this
     */
    public function setMalId($mal_id)
    {
        $this->container['mal_id'] = $mal_id;

        return $this;
    }

    /**
     * Gets hardcover_id
     *
     * @return int
     */
    public function getHardcoverId()
    {
        return $this->container['hardcover_id'];
    }

    /**
     * Sets hardcover_id
     *
     * @param int $hardcover_id hardcover_id
     *
     * @return $this
     */
    public function setHardcoverId($hardcover_id)
    {
        $this->container['hardcover_id'] = $hardcover_id;

        return $this;
    }

    /**
     * Gets metron_id
     *
     * @return int
     */
    public function getMetronId()
    {
        return $this->container['metron_id'];
    }

    /**
     * Sets metron_id
     *
     * @param int $metron_id metron_id
     *
     * @return $this
     */
    public function setMetronId($metron_id)
    {
        $this->container['metron_id'] = $metron_id;

        return $this;
    }

    /**
     * Gets comic_vine_id
     *
     * @return string
     */
    public function getComicVineId()
    {
        return $this->container['comic_vine_id'];
    }

    /**
     * Sets comic_vine_id
     *
     * @param string $comic_vine_id comic_vine_id
     *
     * @return $this
     */
    public function setComicVineId($comic_vine_id)
    {
        $this->container['comic_vine_id'] = $comic_vine_id;

        return $this;
    }

    /**
     * Gets manga_baka_id
     *
     * @return int
     */
    public function getMangaBakaId()
    {
        return $this->container['manga_baka_id'];
    }

    /**
     * Sets manga_baka_id
     *
     * @param int $manga_baka_id manga_baka_id
     *
     * @return $this
     */
    public function setMangaBakaId($manga_baka_id)
    {
        $this->container['manga_baka_id'] = $manga_baka_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
