<?php
/**
 * MetadataSettingsDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Pbxg33k\KavitaClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kavita
 *
 * Kavita provides a set of APIs authenticated via an Auth Key passed in the `x-api-key` header. Generate an Auth Key under User Settings → Manage Auth Keys, paste it into the Authorize panel, and all Try It requests will include it. Assume all fields of a payload are required unless marked optional. Built against v0.9.0.0
 *
 * OpenAPI spec version: 0.9.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.79
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Pbxg33k\KavitaClient;

use PHPUnit\Framework\TestCase;

/**
 * MetadataSettingsDtoTest Class Doc Comment
 *
 * @category    Class
 * @description MetadataSettingsDto
 * @package     Pbxg33k\KavitaClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MetadataSettingsDtoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "MetadataSettingsDto"
     */
    public function testMetadataSettingsDto()
    {
    }

    /**
     * Test attribute "blacklist"
     */
    public function testPropertyBlacklist()
    {
    }

    /**
     * Test attribute "whitelist"
     */
    public function testPropertyWhitelist()
    {
    }

    /**
     * Test attribute "age_rating_mappings"
     */
    public function testPropertyAgeRatingMappings()
    {
    }

    /**
     * Test attribute "field_mappings"
     */
    public function testPropertyFieldMappings()
    {
    }

    /**
     * Test attribute "enabled"
     */
    public function testPropertyEnabled()
    {
    }

    /**
     * Test attribute "enable_extended_metadata_processing"
     */
    public function testPropertyEnableExtendedMetadataProcessing()
    {
    }

    /**
     * Test attribute "enable_summary"
     */
    public function testPropertyEnableSummary()
    {
    }

    /**
     * Test attribute "enable_publication_status"
     */
    public function testPropertyEnablePublicationStatus()
    {
    }

    /**
     * Test attribute "enable_relationships"
     */
    public function testPropertyEnableRelationships()
    {
    }

    /**
     * Test attribute "enable_people"
     */
    public function testPropertyEnablePeople()
    {
    }

    /**
     * Test attribute "enable_start_date"
     */
    public function testPropertyEnableStartDate()
    {
    }

    /**
     * Test attribute "enable_localized_name"
     */
    public function testPropertyEnableLocalizedName()
    {
    }

    /**
     * Test attribute "enable_cover_image"
     */
    public function testPropertyEnableCoverImage()
    {
    }

    /**
     * Test attribute "enable_chapter_summary"
     */
    public function testPropertyEnableChapterSummary()
    {
    }

    /**
     * Test attribute "enable_chapter_release_date"
     */
    public function testPropertyEnableChapterReleaseDate()
    {
    }

    /**
     * Test attribute "enable_chapter_title"
     */
    public function testPropertyEnableChapterTitle()
    {
    }

    /**
     * Test attribute "enable_chapter_publisher"
     */
    public function testPropertyEnableChapterPublisher()
    {
    }

    /**
     * Test attribute "enable_chapter_cover_image"
     */
    public function testPropertyEnableChapterCoverImage()
    {
    }

    /**
     * Test attribute "enable_genres"
     */
    public function testPropertyEnableGenres()
    {
    }

    /**
     * Test attribute "enable_tags"
     */
    public function testPropertyEnableTags()
    {
    }

    /**
     * Test attribute "first_last_people_naming"
     */
    public function testPropertyFirstLastPeopleNaming()
    {
    }

    /**
     * Test attribute "overrides"
     */
    public function testPropertyOverrides()
    {
    }

    /**
     * Test attribute "person_roles"
     */
    public function testPropertyPersonRoles()
    {
    }
}
