<?php
/**
 * UpdatePersonDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Pbxg33k\KavitaClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kavita
 *
 * Kavita provides a set of APIs authenticated via an Auth Key passed in the `x-api-key` header. Generate an Auth Key under User Settings → Manage Auth Keys, paste it into the Authorize panel, and all Try It requests will include it. Assume all fields of a payload are required unless marked optional. Built against v0.9.0.0
 *
 * OpenAPI spec version: 0.9.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.79
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Pbxg33k\KavitaClient;

use PHPUnit\Framework\TestCase;

/**
 * UpdatePersonDtoTest Class Doc Comment
 *
 * @category    Class
 * @description UpdatePersonDto
 * @package     Pbxg33k\KavitaClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UpdatePersonDtoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "UpdatePersonDto"
     */
    public function testUpdatePersonDto()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "cover_image_locked"
     */
    public function testPropertyCoverImageLocked()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "aliases"
     */
    public function testPropertyAliases()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "ani_list_id"
     */
    public function testPropertyAniListId()
    {
    }

    /**
     * Test attribute "mal_id"
     */
    public function testPropertyMalId()
    {
    }

    /**
     * Test attribute "hardcover_id"
     */
    public function testPropertyHardcoverId()
    {
    }

    /**
     * Test attribute "asin"
     */
    public function testPropertyAsin()
    {
    }
}
