<?php
/**
 * VolumeDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Pbxg33k\KavitaClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kavita
 *
 * Kavita provides a set of APIs authenticated via an Auth Key passed in the `x-api-key` header. Generate an Auth Key under User Settings → Manage Auth Keys, paste it into the Authorize panel, and all Try It requests will include it. Assume all fields of a payload are required unless marked optional. Built against v0.9.0.0
 *
 * OpenAPI spec version: 0.9.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.79
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Pbxg33k\KavitaClient;

use PHPUnit\Framework\TestCase;

/**
 * VolumeDtoTest Class Doc Comment
 *
 * @category    Class
 * @description VolumeDto
 * @package     Pbxg33k\KavitaClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class VolumeDtoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "VolumeDto"
     */
    public function testVolumeDto()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "min_number"
     */
    public function testPropertyMinNumber()
    {
    }

    /**
     * Test attribute "max_number"
     */
    public function testPropertyMaxNumber()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "number"
     */
    public function testPropertyNumber()
    {
    }

    /**
     * Test attribute "pages"
     */
    public function testPropertyPages()
    {
    }

    /**
     * Test attribute "pages_read"
     */
    public function testPropertyPagesRead()
    {
    }

    /**
     * Test attribute "last_modified_utc"
     */
    public function testPropertyLastModifiedUtc()
    {
    }

    /**
     * Test attribute "created_utc"
     */
    public function testPropertyCreatedUtc()
    {
    }

    /**
     * Test attribute "created"
     */
    public function testPropertyCreated()
    {
    }

    /**
     * Test attribute "last_modified"
     */
    public function testPropertyLastModified()
    {
    }

    /**
     * Test attribute "series_id"
     */
    public function testPropertySeriesId()
    {
    }

    /**
     * Test attribute "chapters"
     */
    public function testPropertyChapters()
    {
    }

    /**
     * Test attribute "min_hours_to_read"
     */
    public function testPropertyMinHoursToRead()
    {
    }

    /**
     * Test attribute "max_hours_to_read"
     */
    public function testPropertyMaxHoursToRead()
    {
    }

    /**
     * Test attribute "avg_hours_to_read"
     */
    public function testPropertyAvgHoursToRead()
    {
    }

    /**
     * Test attribute "word_count"
     */
    public function testPropertyWordCount()
    {
    }

    /**
     * Test attribute "cover_image"
     */
    public function testPropertyCoverImage()
    {
    }

    /**
     * Test attribute "primary_color"
     */
    public function testPropertyPrimaryColor()
    {
    }

    /**
     * Test attribute "secondary_color"
     */
    public function testPropertySecondaryColor()
    {
    }

    /**
     * Test attribute "ani_list_id"
     */
    public function testPropertyAniListId()
    {
    }

    /**
     * Test attribute "mal_id"
     */
    public function testPropertyMalId()
    {
    }

    /**
     * Test attribute "hardcover_id"
     */
    public function testPropertyHardcoverId()
    {
    }

    /**
     * Test attribute "metron_id"
     */
    public function testPropertyMetronId()
    {
    }

    /**
     * Test attribute "comic_vine_id"
     */
    public function testPropertyComicVineId()
    {
    }

    /**
     * Test attribute "manga_baka_id"
     */
    public function testPropertyMangaBakaId()
    {
    }
}
