<?php
/**
 * ImageApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Pbxg33k\KavitaClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kavita
 *
 * Kavita provides a set of APIs authenticated via an Auth Key passed in the `x-api-key` header. Generate an Auth Key under User Settings → Manage Auth Keys, paste it into the Authorize panel, and all Try It requests will include it. Assume all fields of a payload are required unless marked optional. Built against v0.9.0.0
 *
 * OpenAPI spec version: 0.9.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.79
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Pbxg33k\KavitaClient;

use Pbxg33k\KavitaClient\Configuration;
use Pbxg33k\KavitaClient\ApiException;
use Pbxg33k\KavitaClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ImageApiTest Class Doc Comment
 *
 * @category Class
 * @package  Pbxg33k\KavitaClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ImageApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiImageBookmarkGet
     *
     * Returns image for a given bookmark page.
     *
     */
    public function testApiImageBookmarkGet()
    {
    }

    /**
     * Test case for apiImageChapterCoverGet
     *
     * Returns cover image for Chapter.
     *
     */
    public function testApiImageChapterCoverGet()
    {
    }

    /**
     * Test case for apiImageCollectionCoverGet
     *
     * Returns cover image for Collection.
     *
     */
    public function testApiImageCollectionCoverGet()
    {
    }

    /**
     * Test case for apiImageCoverUploadGet
     *
     * Returns a temp coverupload image.
     *
     */
    public function testApiImageCoverUploadGet()
    {
    }

    /**
     * Test case for apiImageLibraryCoverGet
     *
     * Returns cover image for Library.
     *
     */
    public function testApiImageLibraryCoverGet()
    {
    }

    /**
     * Test case for apiImagePersonCoverGet
     *
     * Returns cover image for Person.
     *
     */
    public function testApiImagePersonCoverGet()
    {
    }

    /**
     * Test case for apiImagePublisherGet
     *
     * Returns the image associated with a publisher.
     *
     */
    public function testApiImagePublisherGet()
    {
    }

    /**
     * Test case for apiImageReadinglistCoverGet
     *
     * Returns cover image for a Reading List.
     *
     */
    public function testApiImageReadinglistCoverGet()
    {
    }

    /**
     * Test case for apiImageSeriesCoverGet
     *
     * Returns cover image for Series.
     *
     */
    public function testApiImageSeriesCoverGet()
    {
    }

    /**
     * Test case for apiImageUserCoverGet
     *
     * Returns cover image for User.
     *
     */
    public function testApiImageUserCoverGet()
    {
    }

    /**
     * Test case for apiImageVolumeCoverGet
     *
     * Returns cover image for Volume.
     *
     */
    public function testApiImageVolumeCoverGet()
    {
    }

    /**
     * Test case for apiImageWebLinkGet
     *
     * Returns the image associated with a web-link.
     *
     */
    public function testApiImageWebLinkGet()
    {
    }
}
