<?php
/**
 * PluginApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Pbxg33k\KavitaClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kavita
 *
 * Kavita provides a set of APIs authenticated via an Auth Key passed in the `x-api-key` header. Generate an Auth Key under User Settings → Manage Auth Keys, paste it into the Authorize panel, and all Try It requests will include it. Assume all fields of a payload are required unless marked optional. Built against v0.9.0.0
 *
 * OpenAPI spec version: 0.9.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.79
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Pbxg33k\KavitaClient;

use Pbxg33k\KavitaClient\Configuration;
use Pbxg33k\KavitaClient\ApiException;
use Pbxg33k\KavitaClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PluginApiTest Class Doc Comment
 *
 * @category Class
 * @package  Pbxg33k\KavitaClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PluginApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiPluginAuthenticatePost
     *
     * Authenticate with the Server given an auth key. This will log you in by returning the user object and the JWT token..
     *
     */
    public function testApiPluginAuthenticatePost()
    {
    }

    /**
     * Test case for apiPluginAuthkeyExpiresGet
     *
     * Returns the expiration (UTC) of the authenticated Auth key (or null if none set).
     *
     */
    public function testApiPluginAuthkeyExpiresGet()
    {
    }

    /**
     * Test case for apiPluginParseBulkPost
     *
     * .
     *
     */
    public function testApiPluginParseBulkPost()
    {
    }

    /**
     * Test case for apiPluginParseGet
     *
     * Parse a string and return Parsed information from it. Does not support any directory fallback parsing.
     *
     */
    public function testApiPluginParseGet()
    {
    }

    /**
     * Test case for apiPluginVersionGet
     *
     * Returns the version of the Kavita install.
     *
     */
    public function testApiPluginVersionGet()
    {
    }
}
