<?php
/**
 * ReadingListApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Pbxg33k\KavitaClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kavita
 *
 * Kavita provides a set of APIs authenticated via an Auth Key passed in the `x-api-key` header. Generate an Auth Key under User Settings → Manage Auth Keys, paste it into the Authorize panel, and all Try It requests will include it. Assume all fields of a payload are required unless marked optional. Built against v0.9.0.0
 *
 * OpenAPI spec version: 0.9.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.79
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Pbxg33k\KavitaClient;

use Pbxg33k\KavitaClient\Configuration;
use Pbxg33k\KavitaClient\ApiException;
use Pbxg33k\KavitaClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ReadingListApiTest Class Doc Comment
 *
 * @category Class
 * @package  Pbxg33k\KavitaClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ReadingListApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiReadingListAllPeopleGet
     *
     * Returns all people in given roles for a reading list.
     *
     */
    public function testApiReadingListAllPeopleGet()
    {
    }

    /**
     * Test case for apiReadingListAllPost
     *
     * Returns reading lists (paginated) for a given user..
     *
     */
    public function testApiReadingListAllPost()
    {
    }

    /**
     * Test case for apiReadingListCreatePost
     *
     * Creates a new List with a unique title. Returns the new ReadingList back.
     *
     */
    public function testApiReadingListCreatePost()
    {
    }

    /**
     * Test case for apiReadingListDelete
     *
     * Deletes a reading list.
     *
     */
    public function testApiReadingListDelete()
    {
    }

    /**
     * Test case for apiReadingListDeleteItemPost
     *
     * Deletes a list item from the list. Item orders will update as a result..
     *
     */
    public function testApiReadingListDeleteItemPost()
    {
    }

    /**
     * Test case for apiReadingListDeleteMultiplePost
     *
     * Delete multiple reading lists in one go.
     *
     */
    public function testApiReadingListDeleteMultiplePost()
    {
    }

    /**
     * Test case for apiReadingListExportAsCblPost
     *
     * Export a Reading List to CBL format.
     *
     */
    public function testApiReadingListExportAsCblPost()
    {
    }

    /**
     * Test case for apiReadingListGet
     *
     * Fetches a single Reading List.
     *
     */
    public function testApiReadingListGet()
    {
    }

    /**
     * Test case for apiReadingListInfoGet
     *
     * Returns random information about a Reading List.
     *
     */
    public function testApiReadingListInfoGet()
    {
    }

    /**
     * Test case for apiReadingListItemsGet
     *
     * Fetches all reading list items for a given list including rich metadata around series, volume, chapters, and progress.
     *
     */
    public function testApiReadingListItemsGet()
    {
    }

    /**
     * Test case for apiReadingListListsForChapterGet
     *
     * Returns all Reading Lists the user has access to that has the given chapter within it..
     *
     */
    public function testApiReadingListListsForChapterGet()
    {
    }

    /**
     * Test case for apiReadingListListsForSeriesGet
     *
     * Returns all Reading Lists the user has access to that the given series within it..
     *
     */
    public function testApiReadingListListsForSeriesGet()
    {
    }

    /**
     * Test case for apiReadingListListsPost
     *
     * Returns reading lists (paginated) for a given user..
     *
     */
    public function testApiReadingListListsPost()
    {
    }

    /**
     * Test case for apiReadingListNameExistsGet
     *
     * Checks if a reading list exists with the name.
     *
     */
    public function testApiReadingListNameExistsGet()
    {
    }

    /**
     * Test case for apiReadingListNextChapterGet
     *
     * Returns the next chapter within the reading list.
     *
     */
    public function testApiReadingListNextChapterGet()
    {
    }

    /**
     * Test case for apiReadingListPeopleGet
     *
     * Returns a list of a given role associated with the reading list.
     *
     */
    public function testApiReadingListPeopleGet()
    {
    }

    /**
     * Test case for apiReadingListPrevChapterGet
     *
     * Returns the prev chapter within the reading list.
     *
     */
    public function testApiReadingListPrevChapterGet()
    {
    }

    /**
     * Test case for apiReadingListPromoteMultiplePost
     *
     * Promote/UnPromote multiple reading lists in one go. Will only update the authenticated user's reading lists and will only work if the user has promotion role.
     *
     */
    public function testApiReadingListPromoteMultiplePost()
    {
    }

    /**
     * Test case for apiReadingListRegenerateCoverPost
     *
     * Regenerates the cover image for a reading list, you must own the given reading list to do this.
     *
     */
    public function testApiReadingListRegenerateCoverPost()
    {
    }

    /**
     * Test case for apiReadingListRemoveReadPost
     *
     * Removes all entries that are fully read from the reading list.
     *
     */
    public function testApiReadingListRemoveReadPost()
    {
    }

    /**
     * Test case for apiReadingListUpdateByChapterPost
     *
     * .
     *
     */
    public function testApiReadingListUpdateByChapterPost()
    {
    }

    /**
     * Test case for apiReadingListUpdateByMultiplePost
     *
     * Adds all chapters from a list of volumes and chapters to a reading list.
     *
     */
    public function testApiReadingListUpdateByMultiplePost()
    {
    }

    /**
     * Test case for apiReadingListUpdateByMultipleSeriesPost
     *
     * Adds all chapters from a list of series to a reading list.
     *
     */
    public function testApiReadingListUpdateByMultipleSeriesPost()
    {
    }

    /**
     * Test case for apiReadingListUpdateBySeriesPost
     *
     * Adds all chapters from a Series to a reading list.
     *
     */
    public function testApiReadingListUpdateBySeriesPost()
    {
    }

    /**
     * Test case for apiReadingListUpdateByVolumePost
     *
     * .
     *
     */
    public function testApiReadingListUpdateByVolumePost()
    {
    }

    /**
     * Test case for apiReadingListUpdatePositionPost
     *
     * Updates an items position.
     *
     */
    public function testApiReadingListUpdatePositionPost()
    {
    }

    /**
     * Test case for apiReadingListUpdatePost
     *
     * Update the properties (title, summary) of a reading list.
     *
     */
    public function testApiReadingListUpdatePost()
    {
    }
}
