<?php
/**
 * ServerApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Pbxg33k\KavitaClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kavita
 *
 * Kavita provides a set of APIs authenticated via an Auth Key passed in the `x-api-key` header. Generate an Auth Key under User Settings → Manage Auth Keys, paste it into the Authorize panel, and all Try It requests will include it. Assume all fields of a payload are required unless marked optional. Built against v0.9.0.0
 *
 * OpenAPI spec version: 0.9.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.79
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Pbxg33k\KavitaClient;

use Pbxg33k\KavitaClient\Configuration;
use Pbxg33k\KavitaClient\ApiException;
use Pbxg33k\KavitaClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ServerApiTest Class Doc Comment
 *
 * @category Class
 * @package  Pbxg33k\KavitaClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ServerApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiServerAnalyzeFilesPost
     *
     * This is a one time task that needs to be ran for v0.7 statistics to work.
     *
     */
    public function testApiServerAnalyzeFilesPost()
    {
    }

    /**
     * Test case for apiServerBackupDbPost
     *
     * Performs an ad-hoc backup of the Database.
     *
     */
    public function testApiServerBackupDbPost()
    {
    }

    /**
     * Test case for apiServerBustKavitaplusCachePost
     *
     * Bust Kavita+ Cache.
     *
     */
    public function testApiServerBustKavitaplusCachePost()
    {
    }

    /**
     * Test case for apiServerChangelogGet
     *
     * Pull the Changelog for Kavita from Github and display.
     *
     */
    public function testApiServerChangelogGet()
    {
    }

    /**
     * Test case for apiServerCheckForUpdatesGet
     *
     * Checks for updates and pushes an event to the UI.
     *
     */
    public function testApiServerCheckForUpdatesGet()
    {
    }

    /**
     * Test case for apiServerCheckOutOfDateGet
     *
     * Returns how many versions out of date this install is.
     *
     */
    public function testApiServerCheckOutOfDateGet()
    {
    }

    /**
     * Test case for apiServerCheckUpdateGet
     *
     * Checks for updates, if no updates that are > current version installed, returns null.
     *
     */
    public function testApiServerCheckUpdateGet()
    {
    }

    /**
     * Test case for apiServerCleanupPost
     *
     * Performs the nightly maintenance work on the Server. Can be heavy..
     *
     */
    public function testApiServerCleanupPost()
    {
    }

    /**
     * Test case for apiServerCleanupWantToReadPost
     *
     * Performs an ad-hoc cleanup of Want To Read, by removing want to read series for users, where the series are fully read and in Completed publication status..
     *
     */
    public function testApiServerCleanupWantToReadPost()
    {
    }

    /**
     * Test case for apiServerClearCachePost
     *
     * Performs an ad-hoc cleanup of Cache.
     *
     */
    public function testApiServerClearCachePost()
    {
    }

    /**
     * Test case for apiServerClearMediaAlertsPost
     *
     * Deletes all media errors.
     *
     */
    public function testApiServerClearMediaAlertsPost()
    {
    }

    /**
     * Test case for apiServerConvertMediaPost
     *
     * Triggers the scheduling of the convert media job. This will convert all media to the target encoding (except for PNG). Only one job will run at a time..
     *
     */
    public function testApiServerConvertMediaPost()
    {
    }

    /**
     * Test case for apiServerJobsGet
     *
     * Returns a list of reoccurring jobs. Scheduled ad-hoc jobs will not be returned..
     *
     */
    public function testApiServerJobsGet()
    {
    }

    /**
     * Test case for apiServerLogsGet
     *
     * Downloads all the log files via a zip.
     *
     */
    public function testApiServerLogsGet()
    {
    }

    /**
     * Test case for apiServerMediaErrorsGet
     *
     * Returns a list of issues found during scanning or reading in which files may have corruption or bad metadata (structural metadata).
     *
     */
    public function testApiServerMediaErrorsGet()
    {
    }

    /**
     * Test case for apiServerServerInfoSlimGet
     *
     * Returns non-sensitive information about the current system.
     *
     */
    public function testApiServerServerInfoSlimGet()
    {
    }

    /**
     * Test case for apiServerSyncThemesPost
     *
     * Runs the Sync Themes task.
     *
     */
    public function testApiServerSyncThemesPost()
    {
    }
}
