<?php
/**
 * ThemeApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Pbxg33k\KavitaClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kavita
 *
 * Kavita provides a set of APIs authenticated via an Auth Key passed in the `x-api-key` header. Generate an Auth Key under User Settings → Manage Auth Keys, paste it into the Authorize panel, and all Try It requests will include it. Assume all fields of a payload are required unless marked optional. Built against v0.9.0.0
 *
 * OpenAPI spec version: 0.9.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.79
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Pbxg33k\KavitaClient;

use Pbxg33k\KavitaClient\Configuration;
use Pbxg33k\KavitaClient\ApiException;
use Pbxg33k\KavitaClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ThemeApiTest Class Doc Comment
 *
 * @category Class
 * @package  Pbxg33k\KavitaClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ThemeApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiThemeBrowseGet
     *
     * Browse themes that can be used on this server.
     *
     */
    public function testApiThemeBrowseGet()
    {
    }

    /**
     * Test case for apiThemeDelete
     *
     * Attempts to delete a theme. If already in use by users, will not allow.
     *
     */
    public function testApiThemeDelete()
    {
    }

    /**
     * Test case for apiThemeDownloadContentGet
     *
     * Returns css content to the UI. UI is expected to escape the content.
     *
     */
    public function testApiThemeDownloadContentGet()
    {
    }

    /**
     * Test case for apiThemeDownloadThemePost
     *
     * Downloads a SiteTheme from upstream.
     *
     */
    public function testApiThemeDownloadThemePost()
    {
    }

    /**
     * Test case for apiThemeGet
     *
     * .
     *
     */
    public function testApiThemeGet()
    {
    }

    /**
     * Test case for apiThemeUpdateDefaultPost
     *
     * .
     *
     */
    public function testApiThemeUpdateDefaultPost()
    {
    }

    /**
     * Test case for apiThemeUploadThemePost
     *
     * Uploads a new theme file.
     *
     */
    public function testApiThemeUploadThemePostForm()
    {
    }
}
